### ISSUE TITLE
doesn't work in angular2 v2.4.0

### ISSUE THREAD

**Issue by johnny2002** [akveo/ng2-smart-table#132]
Seems it doesn't work in lastest angular2. 

 "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",

**Comment by johnny2002** [comment]
lots of problems:
1. @angular/http/src/url_search_params"' has no exported member 'RequestOptionsArgs'
2. can't load required js, html, css properly.

**Comment by johnny2002** [comment]
![ng2-table](https://cloud.githubusercontent.com/assets/8021759/22026529/03223c72-dd0c-11e6-9cdc-5f22ad5f29d0.png)
more problems here.

**Comment by brian-singer** [comment]
damn, I just wanted to give this smart table a go, but yeah.
I also get different problems:

1. added missing "node-sass": "4.3.0"
2. Included Ng2SmartTableComponent (not in documentation)
3. Uncaught Error: Module build failed: Error: /Users/brian.singer/playground/git/chopsuey-drms-ui/src/app/main/main.module.ts (8,33): Cannot find module 'ng2-smart-table/components/filter/filter.component'.)

Add3. is because the module is not properly declaring the components dependencies and Ng2SmartTableModule is not even a module......
