### ISSUE TITLE
very slow when it comes to +20 lines with +10 columns ?

### ISSUE THREAD

**Issue by amineparis** [akveo/ng2-smart-table#189]
it makes all the app slow ! any ideas of how to optimis performance ? is theire way to stop watching the source (one time binding) ?

**Comment by nnixaa** [comment]
@damnko would you like to take a look? Sounds like a  challenge.

**Comment by damnko** [comment]
@nnixaa Yep it will indeed be a challenge.
#184 will also benefit from this solution so I would like to give priority to this issue.

**Comment by damnko** [comment]
@LexZhukov or @nnixaa do you remember what's the use case of this method?

https://github.com/akveo/ng2-smart-table/blob/8a54dea141041d8db19f42430db46d2a2c2dcae8/src/ng2-smart-table/components/cell/cell-view-mode/view-cell.component.ts#L20-L22

I wanted to focus first on all `ngOnChanges` to see if they can be removed/replaced with something less obtrusive, otherwise I will try to change the _detectionStrategy_ but I noticed quite a difference when I removed that method.
Thanks

**Comment by nnixaa** [comment]
@damnko there is a feature when you can specify a `renderer` function to a column, which is not really a renderer, but just some function which accepts the rendered cell HTML into it and can change this HTML in the runtime (so that you can access cell HTML element in this function and do with it whatever you want, bypassing angular).
Basically it's more of a workaround rather than a good solution, we planned to replace this with a custom cell viewer component feature.

**Comment by sla-shi** [comment]
@damnko thanks for the workaround, it really helped. I commented out the line 21 in view-cell.component.ts while waiting for the fix in the coming update.

**Comment by damnko** [comment]
@nnixaa thanks for sharing that info, I was also thinking why do we have to check for that on every `ngOnChanges` cycle? How does it feel if I start to work on a custom component to eventually render the cell content so we can get rid of this entirely?

**Comment by nnixaa** [comment]
@damnko this sounds perfectly right! 👍 
I believe we can utilize the same approach as for the custom editor component.

**Comment by damnko** [comment]
@nnixaa yep I believe so, will keep you posted

**Comment by Deilan** [comment]
How is it going?

**Comment by yangwen2** [comment]
I have the smart table component injected into the DOM conditionally via an *ngIf.  When the smart table is part of the DOM anywhere in the screen, the mouseOver related UI updates drops from ~60fps to ~2fps.  This test was carried out with ~150 rows in the smart table, with pagination disabled.

Looking further with Chrome timelines, it appears when smart table is rendered on the screen, a tremendous amount of processing is done in Angular 2's change detection logic.  ApplicationRef_.tick() specifically.

Does this problem sound familiar for anyone else?

**Comment by kkapil24** [comment]
Is there update on this issue fix?

**Comment by Vingtoft** [comment]
Just spend hours configuring the table before I noticed this issue. The table is basically unusable until this is fixed. 

Is there any progress?

**Comment by kyrodabase** [comment]
looks like critical issue :/ anyway - well done guys, loving this tool

**Comment by j-soliduslink** [comment]
we like the smart table a lot, would be great if you could fix the performance issue soon

**Comment by vlapo** [comment]
Same problem here.

@damnko @nnixaa I think I found bottleneck:
https://github.com/akveo/ng2-smart-table/blob/89d8acef62bb82efc41e771d40c2bf5c4ced83b1/src/ng2-smart-table/lib/helpers.ts#L90

```getDeepFromObject``` is called over ```getSetting``` and ```deepExtend``` really slow searching. Why did you clone object? I think use lodash ```_.get``` function should be better solution.
There is also question why ```getSetting``` is called so much in endless loop.

**Comment by nnixaa** [comment]
Hey Guys, we are investigating the issue, and hopefully planning to release a fix soon.

**Comment by lexzhukov** [comment]
This bug is fixed in https://github.com/akveo/ng2-smart-table/commit/69e883c454405ca4b9dac4ee35cd9ee855f2c9f1. Try to update to the latest 1.2.0 version of ng2-smart-table.

**Comment by vlapo** [comment]
Hi @lexzhukov, thnx for fix, but I have inifinite loop problem now: 
```
angular.js:13236 TypeError: this.inputControl.valueChanges.skip is not a function
    at SelectFilterComponent.ngOnInit (table.umd.js:1615)
    at checkAndUpdateDirectiveInline (provider.ts:275)
    at checkAndUpdateNodeInline (view.ts:456)
    at checkAndUpdateNode (view.ts:417)
    at debugCheckAndUpdateNode (services.ts:235)
    at debugCheckDirectivesFn (services.ts:294)
    at Object.eval [as updateDirectives] (FilterComponent.html:3)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:273)
    at checkAndUpdateView (view.ts:345)
    at callViewAction (view.ts:700)
```
I think it is something like this https://github.com/akveo/ng2-smart-table/issues/229

**Comment by lexzhukov** [comment]
@vlapo this is fixed. Try to install v1.2.1.

**Comment by vlapo** [comment]
@lexzhukov greate work!👍  

I think performance is better :) Of course, I don't have so many columns but with 6 columns and 30 rows there is no lagging.

**Comment by lvqing1122** [comment]
Hi @lexzhukov ,
After update to v1.2.1, I still have performance issue in IE. I have 9 columns and 30+ rows in smart table. 7 of columns are custom. But in chrome, the performance issue is not existed.

**Comment by cyborgdoom** [comment]
We had this very same issue in another app it turns out the use of ngFor is the root cause in IE 11 you need to add  trackBy: trackByFn ... trackByFn being a function  in your component like so 

 trackByFn(index, item) {
    return index; // or item.id
  }

Once I add that into my component the page improved quite a bit from 2-3 minute load time down to 2-3 seconds.. Lots of records :)
