### ISSUE TITLE
 ERROR in node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(2,48): error TS1039: Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by JordyEspejel** [akveo/ng2-smart-table#1074]
i´m working with Angular 6 2.9, i´m trying to use the ng2-smart-table library. i got  this issues : 

**node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(3,46): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(4,48): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(5,49): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(6,50): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(7,43): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-smart-table/lib/lib/data-source/server/server-source.conf.d.ts(8,42): error TS1039: Initializers are not allowed in ambient contexts.**

this is part of the package.json:

 "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "ng2-smart-table": "^1.5.0",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.9",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng2-completer": "^3.0.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
Hope you can help

**Comment by Basit-qc** [comment]
Fixed same issue using: https://github.com/pnp/pnpjs/issues/299#issuecomment-432216018
